/**
 * COGNITIVE PLATFORM - UNIFIED ERROR CODES
 * 
 * Standard error codes used across all services for consistent error handling.
 */

export const ErrorCode = {
  // Service errors
  SERVICE_NOT_FOUND: 'SERVICE_NOT_FOUND',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  SERVICE_OVERLOADED: 'SERVICE_OVERLOADED',
  SERVICE_TIMEOUT: 'SERVICE_TIMEOUT',
  CIRCUIT_BREAKER_OPEN: 'CIRCUIT_BREAKER_OPEN',
  
  // Request errors
  INVALID_REQUEST: 'INVALID_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  
  // Authentication & Authorization
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  
  // Resource errors
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  CONFLICT: 'CONFLICT',
  
  // Database errors
  DATABASE_ERROR: 'DATABASE_ERROR',
  DATABASE_CONNECTION_FAILED: 'DATABASE_CONNECTION_FAILED',
  QUERY_ERROR: 'QUERY_ERROR',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
  
  // Cache errors
  CACHE_ERROR: 'CACHE_ERROR',
  CACHE_CONNECTION_FAILED: 'CACHE_CONNECTION_FAILED',
  
  // External service errors
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  EXTERNAL_SERVICE_TIMEOUT: 'EXTERNAL_SERVICE_TIMEOUT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  
  // Process/Pipeline errors
  PROCESS_FAILED: 'PROCESS_FAILED',
  PROCESS_TIMEOUT: 'PROCESS_TIMEOUT',
  PROCESS_CANCELLED: 'PROCESS_CANCELLED',
  INVALID_STATE: 'INVALID_STATE',
  
  // Graph/OSINT errors
  GRAPH_ANALYSIS_FAILED: 'GRAPH_ANALYSIS_FAILED',
  OSINT_TOOL_FAILED: 'OSINT_TOOL_FAILED',
  OSINT_TOOL_NOT_INSTALLED: 'OSINT_TOOL_NOT_INSTALLED',
  
  // File errors
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_WRITE_ERROR: 'FILE_WRITE_ERROR',
  FILE_READ_ERROR: 'FILE_READ_ERROR',
  
  // Internal errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type ErrorCodeType = typeof ErrorCode[keyof typeof ErrorCode];

/**
 * HTTP status code mapping for errors
 */
export const ErrorStatusMap: Record<ErrorCodeType, number> = {
  SERVICE_NOT_FOUND: 503,
  SERVICE_UNAVAILABLE: 503,
  SERVICE_OVERLOADED: 503,
  SERVICE_TIMEOUT: 504,
  CIRCUIT_BREAKER_OPEN: 503,
  
  INVALID_REQUEST: 400,
  VALIDATION_ERROR: 400,
  MISSING_REQUIRED_FIELD: 400,
  INVALID_PAYLOAD: 400,
  
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  INVALID_TOKEN: 401,
  TOKEN_EXPIRED: 401,
  
  NOT_FOUND: 404,
  ALREADY_EXISTS: 409,
  CONFLICT: 409,
  
  DATABASE_ERROR: 500,
  DATABASE_CONNECTION_FAILED: 500,
  QUERY_ERROR: 500,
  TRANSACTION_FAILED: 500,
  
  CACHE_ERROR: 500,
  CACHE_CONNECTION_FAILED: 500,
  
  EXTERNAL_SERVICE_ERROR: 502,
  EXTERNAL_SERVICE_TIMEOUT: 504,
  RATE_LIMIT_EXCEEDED: 429,
  
  PROCESS_FAILED: 500,
  PROCESS_TIMEOUT: 504,
  PROCESS_CANCELLED: 499,
  INVALID_STATE: 400,
  
  GRAPH_ANALYSIS_FAILED: 500,
  OSINT_TOOL_FAILED: 500,
  OSINT_TOOL_NOT_INSTALLED: 400,
  
  FILE_NOT_FOUND: 404,
  FILE_WRITE_ERROR: 500,
  FILE_READ_ERROR: 500,
  
  INTERNAL_ERROR: 500,
  UNKNOWN_ERROR: 500,
};
